CRITICAL - 2022-04-17 03:54:58 --> Invalid argument supplied for foreach()
#0 C:\xampp\htdocs\ci\app\Views\home.php(83): CodeIgniter\Debug\Exceptions->errorHandler(2, 'Invalid argumen...', 'C:\\xampp\\htdocs...', 83, Array)
#1 C:\xampp\htdocs\ci\system\View\View.php(210): include('C:\\xampp\\htdocs...')
#2 C:\xampp\htdocs\ci\system\View\View.php(213): CodeIgniter\View\View->CodeIgniter\View\{closure}()
#3 C:\xampp\htdocs\ci\system\Common.php(1089): CodeIgniter\View\View->render('home', Array, true)
#4 C:\xampp\htdocs\ci\app\Controllers\Home.php(9): view('home')
#5 C:\xampp\htdocs\ci\system\CodeIgniter.php(832): App\Controllers\Home->index()
#6 C:\xampp\htdocs\ci\system\CodeIgniter.php(419): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Home))
#7 C:\xampp\htdocs\ci\system\CodeIgniter.php(326): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#8 C:\xampp\htdocs\ci\public\index.php(37): CodeIgniter\CodeIgniter->run()
#9 C:\xampp\htdocs\ci\system\Commands\Server\rewrite.php(43): require_once('C:\\xampp\\htdocs...')
#10 {main}
ERROR - 2022-04-17 03:56:55 --> Error connecting to the database: Access denied for user ''@'localhost' (using password: NO)
CRITICAL - 2022-04-17 03:56:55 --> Unable to connect to the database.
Main connection [MySQLi]: Access denied for user ''@'localhost' (using password: NO)
#0 C:\xampp\htdocs\ci\system\Database\BaseConnection.php(577): CodeIgniter\Database\BaseConnection->initialize()
#1 C:\xampp\htdocs\ci\system\Database\BaseBuilder.php(1455): CodeIgniter\Database\BaseConnection->query('SELECT *\nFROM `...', Array, false)
#2 C:\xampp\htdocs\ci\system\Model.php(183): CodeIgniter\Database\BaseBuilder->get()
#3 C:\xampp\htdocs\ci\system\BaseModel.php(584): CodeIgniter\Model->doFindAll(0, 0)
#4 C:\xampp\htdocs\ci\app\Controllers\Home.php(15): CodeIgniter\BaseModel->findAll()
#5 C:\xampp\htdocs\ci\system\CodeIgniter.php(832): App\Controllers\Home->index()
#6 C:\xampp\htdocs\ci\system\CodeIgniter.php(419): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Home))
#7 C:\xampp\htdocs\ci\system\CodeIgniter.php(326): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#8 C:\xampp\htdocs\ci\public\index.php(37): CodeIgniter\CodeIgniter->run()
#9 C:\xampp\htdocs\ci\system\Commands\Server\rewrite.php(43): require_once('C:\\xampp\\htdocs...')
#10 {main}
ERROR - 2022-04-17 03:58:02 --> Table 'pendidikan.pendidikan' doesn't exist
CRITICAL - 2022-04-17 03:58:02 --> Call to a member function getResult() on bool
#0 C:\xampp\htdocs\ci\system\BaseModel.php(584): CodeIgniter\Model->doFindAll(0, 0)
#1 C:\xampp\htdocs\ci\app\Controllers\Home.php(15): CodeIgniter\BaseModel->findAll()
#2 C:\xampp\htdocs\ci\system\CodeIgniter.php(832): App\Controllers\Home->index()
#3 C:\xampp\htdocs\ci\system\CodeIgniter.php(419): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Home))
#4 C:\xampp\htdocs\ci\system\CodeIgniter.php(326): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#5 C:\xampp\htdocs\ci\public\index.php(37): CodeIgniter\CodeIgniter->run()
#6 C:\xampp\htdocs\ci\system\Commands\Server\rewrite.php(43): require_once('C:\\xampp\\htdocs...')
#7 {main}
ERROR - 2022-04-17 03:58:05 --> Table 'pendidikan.pendidikan' doesn't exist
CRITICAL - 2022-04-17 03:58:05 --> Call to a member function getResult() on bool
#0 C:\xampp\htdocs\ci\system\BaseModel.php(584): CodeIgniter\Model->doFindAll(0, 0)
#1 C:\xampp\htdocs\ci\app\Controllers\Home.php(15): CodeIgniter\BaseModel->findAll()
#2 C:\xampp\htdocs\ci\system\CodeIgniter.php(832): App\Controllers\Home->index()
#3 C:\xampp\htdocs\ci\system\CodeIgniter.php(419): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Home))
#4 C:\xampp\htdocs\ci\system\CodeIgniter.php(326): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#5 C:\xampp\htdocs\ci\public\index.php(37): CodeIgniter\CodeIgniter->run()
#6 C:\xampp\htdocs\ci\system\Commands\Server\rewrite.php(43): require_once('C:\\xampp\\htdocs...')
#7 {main}
ERROR - 2022-04-17 04:01:22 --> Table 'pendidikan.pendidikan' doesn't exist
CRITICAL - 2022-04-17 04:01:22 --> Table 'pendidikan.pendidikan' doesn't exist
#0 C:\xampp\htdocs\ci\system\Database\MySQLi\Connection.php(292): mysqli->query('SELECT *\nFROM `...', 0)
#1 C:\xampp\htdocs\ci\system\Database\BaseConnection.php(670): CodeIgniter\Database\MySQLi\Connection->execute('SELECT *\nFROM `...')
#2 C:\xampp\htdocs\ci\system\Database\BaseConnection.php(598): CodeIgniter\Database\BaseConnection->simpleQuery('SELECT *\nFROM `...')
#3 C:\xampp\htdocs\ci\system\Database\BaseBuilder.php(1455): CodeIgniter\Database\BaseConnection->query('SELECT *\nFROM `...', Array, false)
#4 C:\xampp\htdocs\ci\system\Model.php(183): CodeIgniter\Database\BaseBuilder->get()
#5 C:\xampp\htdocs\ci\system\BaseModel.php(584): CodeIgniter\Model->doFindAll(0, 0)
#6 C:\xampp\htdocs\ci\app\Controllers\Home.php(15): CodeIgniter\BaseModel->findAll()
#7 C:\xampp\htdocs\ci\system\CodeIgniter.php(832): App\Controllers\Home->index()
#8 C:\xampp\htdocs\ci\system\CodeIgniter.php(419): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Home))
#9 C:\xampp\htdocs\ci\system\CodeIgniter.php(326): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#10 C:\xampp\htdocs\ci\public\index.php(37): CodeIgniter\CodeIgniter->run()
#11 C:\xampp\htdocs\ci\system\Commands\Server\rewrite.php(43): require_once('C:\\xampp\\htdocs...')
#12 {main}
